ad:
  common:
    account: linchenxiao@corp.netease.com
    dspId: 10101
    groupId: 100003
  url:
    yunying: http://10.200.132.146:10010/
    maisui: http://10.200.132.146:10020/
    maitian: http://10.200.132.146:60001/
  setting:
    suffix: _test
